# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
INSTALL_LOCATION = $(TOP)
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

USR_CFLAGS += -D$(T_A)

SRCS.c += ../alm.c ../alm_test.c

USR_INCLUDES += -I$(INSTALL_LOCATION)/include

INC += alm.h

LIBNAME = almLib
LIBOBJS += alm.o

TARGETS += alm_test.o

include $(TOP)/config/RULES.Vx
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
