# Makefile.Vx
TOP = ../..
include $(TOP)/config/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# to avoid warnings about long longs
CMPLR=ANSI

INC += almLib.h

DBDINSTALL = almLib.LIBOBJS almLib.LDOBJS

SRCS.c += ../almLib.c

LIBOBJS += almLib.o

LIBNAME = almLib

include $(TOP)/config/RULES.Vx
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
