TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

INC += almLib.h

LIBRARY_IOC_vxWorks = alm

LIB_SRCS += almLib.c almRegisterCmds.c

DBD += alm.dbd

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
